spring.application.name=wanted-item-app

spring.datasource.url=jdbc:postgresql://localhost:5432/wanted-item-app
spring.datasource.username=postgres
spring.datasource.password=qweasd123
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml

mybatis.configuration.map-underscore-to-camel-case=true